services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: legacymonolith
    ports:
      - "6000:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql